blueprint:
  name: "Electricity cost per device"
  description: "This automation updates an input sensor with the total spent amount per device. It uses a sensor with the current price to update itself. Use a meter to set up tariffs and consider using the giovdi/ha-prices blueprint to automatize the switch between tariffs."
  source_url: https://github.com/giovdi/ha-electricity-cost/blob/main/home_electricity_cost.yaml
  domain: automation

  input:
    tariff_current_sensor:
      name: "Current electricity price"
      description: "Sensor with the current electricity price"
      selector:
        entity:
          filter:
            domain: sensor
            device_class: monetary
    energy_sensors:
      name: "Energy sensors"
      description: "Sensors that the automation will read"
      selector:
        entity:
          multiple: true
          filter:
            domain: sensor
            device_class: energy
    output_sensor:
      name: "Output sensor"
      description: "Select a sensor where the energy cost will be stored"
      selector:
        entity:
          filter:
            domain: input_number
          
mode: restart
max_exceeded: silent

variables:
  tariff_current_sensor: !input tariff_current_sensor

trigger:
  - platform: state
    entity_id: !input energy_sensors

action:
  - service: input_number.set_value
    target:
      entity_id: !input output_sensor
    data:
      value: >-
        {% set price  = states(tariff_current_sensor) | float(0) %}
        {% set delta = trigger.to_state.state | float(0) - trigger.from_state.state | float(0) %}
        {% set previous = (this.state if this is defined else 0) | float(0) %}
        {% if delta > 0 %}
          {{ previous + delta * price }}
        {% else %}
          {{ previous }}
        {% endif %}
        
